export const preguntas = [
  'Cambios de humor irritabilidad',
  'Cambios en el apetito',
  'Cambios en la conducta sexual',
  'Corazon acelerado o palpitaciones',
  'Dolor de tripa nauseas o vomitos',
  'Evitar determinadas situaciones',
  'Faltas de memoria te cuesta recordar cosas',
  'Fumar o beber mas de lo habitual',
  'Incapacidad de pensar claramente o bloqueo mental',
  'Inseguridad a la hora de tomar decisiones (incluso simples)',
  'Llorar mas de lo habitual',
  'Nivel de Ansiedad',
  'Pensamientos anticipatorios negativos o catastroficos',
  'Pensamientos rumiativos (le das muchas vueltas a las cosas)',
  'Presion en el pecho sensacion de ahogo o de que cuesta respirar',
  'Problemas de concentracion (incluso en tareas sencillas)',
  'Problemas para descansar y para dormir',
  'Puntaje Total',
  'Sensacion de agobio de angustia',
  'Sensacion de fatiga',
  'Sensacion de inquietud nervios intranquilidad',
  'Tension muscular o dolores en algunas partes del cuerpo',
];
